name: gha event demo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - labeled

jobs:
  setup-vars:
    runs-on: ubuntu-latest
    outputs:
      preview: ${{ steps.setup-vars.outputs.preview }}
      unstable: ${{ steps.setup-vars.outputs.unstable }}
      stable: ${{ steps.setup-vars.outputs.stable }}
      config_only: ${{ steps.setup-vars.outputs.config_only }}
      config_preview: ${{ steps.setup-vars.outputs.config_preview }}
      config_dev: ${{ steps.setup-vars.outputs.config_dev }}
      config_prod: ${{ steps.setup-vars.outputs.config_prod }}
      config_stable: ${{ steps.setup-vars.outputs.config_stable }}
    steps:
      - uses: actions/checkout@v4
      - name: setup vars
        id: setup-vars
        env:
          GITHUB_BEFORE: "${{ github.event.before }}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "==> Setting variables from github event context..."
          set -x
          # initialize flags
          unstable="false"
          preview="false"
          stable="false"

          config_only="false"
          config_preview="false"
          config_dev="false"
          config_prod="false"
          config_stable="false"

          # patterns to match config files
          config_pattern='^(k8s/helm-values/)'
          config_ignore='(.github|scripts|scripts-ext)'

          # get base ref for main or PR
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then

            echo "On main branch."
            echo "Setting stable=true"
            stable="true"

            echo "Setting base ref to $GITHUB_BEFORE"
            github_base_ref="$GITHUB_BEFORE"

          elif [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then

            echo "Pull request event"
            labels=$(jq -r '.pull_request.labels[].name' "$GITHUB_EVENT_PATH")

            # set preview=true only if 'preview' label exists and 'unstable' label does not
            # unstable superscedes preview when both are present
            if grep -q "^preview$" <<<"$labels" && ! grep -q "^unstable$" <<<"$labels"; then
                echo "Label 'preview' found and 'unstable' label NOT found. Setting preview=true"
                preview="true"
            fi

            if grep -q "^unstable$" <<<"$labels"; then
                echo "Label 'preview' found. Setting unstable=true"
                unstable="true"
            fi


            echo "Setting base ref to ${{ github.base_ref }}"
            github_base_ref=$(gh api repos/${{ github.repository }}/commits/${{ github.base_ref }} --jq '.sha')
          fi


          config_only(){
          # return true when only app config has changed
            local github_base_ref="$1"
            local pattern="$2"
            local ignore="$3"

            git fetch origin "$github_base_ref"

            local _files
            _files="$(git diff --name-only "${github_base_ref}" HEAD)"
            local files
            files="$(grep -vE "$ignore" <<<"${FILES:-$_files}")"

            local changed_config="false"
            local changed_artifact="false"
            local config_only="false"

            if [[ -z "$files" ]]; then
              echo "$config_only"
             return
            fi

            if grep -qvE "$pattern" <<<"$files"; then
              echo "matched artifact build changes." >&2
              changed_artifact="true"
            fi

            if grep -qE "$pattern" <<<"$files"; then
              echo "matched config changes." >&2
              changed_config="true"
            fi

            if [[ "$changed_artifact" == "false" ]] && [[ "$changed_config" == "true" ]]; then
              config_only="true"
            fi

            echo "$config_only"
          }

          detect_config_env_changes(){
          # return true when only app config has changed
            local github_base_ref="$1"
            local pattern="$2"
            local ignore="$3"

            git fetch origin "$github_base_ref"

            local _files files
            _files="$(git diff --name-only "${github_base_ref}" HEAD)"
            files="$(grep -vE "$config_ignore" <<<"${FILES:-$_files}")"


            config_only="$(config_only "$github_base_ref" "$config_pattern" "$config_ignore")"
            # Reset output flags
            config_preview="false"
            config_dev="false"
            config_prod="false"
            config_stable="false"


            if [[ "$config_only" != "true" ]]; then
              return
            fi

            # Directly check if each env was updated
            local preview_updated dev_updated prod_updated
            preview_updated="false"
            dev_updated="false"
            prod_updated="false"

            if grep -qE "${pattern}.*preview" <<<"$files"; then
              preview_updated="true"
            fi
            if grep -qE "${pattern}.*dev" <<<"$files"; then
              dev_updated="true"
            fi
            if grep -qE "${pattern}.*prod" <<<"$files"; then
              prod_updated="true"
            fi

            # Apply business rules for outputs
            if [[ "$preview" == "true" && "$preview_updated" == "true" ]]; then
              config_preview="true"
            fi
            if { [[ "$unstable" == "true" && "$dev_updated" == "true" ]] || [[ "$stable" == "true" && "$dev_updated" == "true" ]]; }; then
              config_dev="true"
            fi
            if [[ "$stable" == "true" && "$prod_updated" == "true" ]]; then
              config_prod="true"
            fi
            if [[ "$stable" == "true" && "$dev_updated" == "true" && "$prod_updated" == "true" ]]; then
              config_stable="true"
            fi
          }


          detect_config_env_changes "$github_base_ref" "$config_pattern" "$config_ignore"


          # --- Output summary ---
          echo "config_only=$config_only"
          echo "config_preview=$config_preview"
          echo "config_dev=$config_dev"
          echo "config_prod=$config_prod"
          echo "config_stable=$config_stable"
          echo "preview=$preview"
          echo "unstable=$unstable"
          echo "stable=$stable"

          {
            echo "config_only=$config_only"
            echo "config_preview=$config_preview"
            echo "config_dev=$config_dev"
            echo "config_prod=$config_prod"
            echo "config_stable=$config_stable"
            echo "preview=$preview"
            echo "unstable=$unstable"
            echo "stable=$stable"
          } >> "$GITHUB_OUTPUT"

  deploy-preview:
    runs-on: ubuntu-latest
    needs: setup-vars
    if: needs.setup-vars.outputs.preview == 'true' && (
          needs.setup-vars.outputs.config_only != 'true'
          || needs.setup-vars.outputs.config_preview == 'true'
        )
    permissions:
      pull-requests: write
    steps:
      - name: deploy-preview
        run: echo "Preview is enabled"
      - name: notify
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const sha = context.payload.pull_request?.head?.sha?.substring(0, 7) || context.sha.substring(0, 7);
            const actor = context.actor;
            const message = `
            ### ⛵ Preview Deployment Triggered

            Pipeline Execution: 
            Commit: ${sha}
            Triggered by: ${actor}`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            })

  deploy-unstable:
    runs-on: ubuntu-latest
    needs: setup-vars
    if: needs.setup-vars.outputs.unstable == 'true' && (
          needs.setup-vars.outputs.config_only != 'true'
          || needs.setup-vars.outputs.config_dev == 'true'
        )
    permissions:
      pull-requests: write
    steps:
      - name: deploy-unstable
        if: needs.setup-vars.outputs.unstable == 'true'
        run: echo "Unstable is enabled"
      - name: notify
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const sha = context.payload.pull_request?.head?.sha?.substring(0, 7) || context.sha.substring(0, 7);
            const actor = context.actor;
            const message = `
            ### ⛵ Unstable Deployment Triggered

            Pipeline Execution:
            Commit: ${sha}
            Triggered by: ${actor}`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            })

  deploy-stable:
    runs-on: ubuntu-latest
    needs: setup-vars
    if: needs.setup-vars.outputs.stable == 'true' && needs.setup-vars.outputs.config_only != 'true'
    steps:
      - name: deploy-stable
        if: needs.setup-vars.outputs.stable == 'true'
        run: echo "Stable is enabled"
